### ISSUE TITLE
Provide docker context

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#8]
This repo should provide a docker context that can be used in docker compose like so:
```yaml
services:
  flask-data-portal:
    build:
      context: https://github.com/hubmapconsortium/flask-data-portal.git#v0.0.x:context
```
Note:
- [`context` in docker-compose.yml can specify urls.](https://docs.docker.com/compose/compose-file/#context)
- [These urls can specify tags and subtrees.](https://docs.docker.com/engine/reference/commandline/build/#git-repositories)
- I prefer pinning to git versions, rather than having the dockerhub intermediate. While this does mean a build will be required, rather than just taking an image, I think the simplicity is worth it.
- Blocked on availability of shared docker base image: Our services have a shared set of concerns, so we shouldn't duplicate the work of setting up the containers. Bill wrote:
  > For our stuff we were standardizing on CentOS because that is what we have experience with, run in prod (will be less likely to have a kernel conflict) and track for security updates.
Also we are standardizing on uWSGI or Nginx in front of uWSGI because of the architecture of our API Gateway. ...  I think it will be easy for Zhou to put a standard image together once he's got time.
